### ISSUE TITLE
Unexpected TemplateSyntaxError

### ISSUE THREAD

**Issue by DeFidelity** [zelenij/django-bootstrap-v5#11]
After loading the 'bootstrap5' in my template I rendered the csrf token, {%bootstrap_form form%} . when i run the server i am getting an Unexpected TemplateSyntaxError that is telling me that bootstrap_form expected an endblock. here is my template

```
`{% extends "base.html" %}
{% load bootstrap5 %}
{% block content %}
<div class="container">
  <h1>Log In</h1>
  <form method="POST" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
          <button type="submit" class="btn btn-primary">login</button>
      {% endbuttons %}
  </form>
</div>
{% endblock content %}
````

And here is the error I am getting
`TemplateSyntaxError at /account/login/
Invalid block tag on line 8: 'bootsrap_form', expected 'endblock'. Did you forget to register or load this tag?`
Error details:
```
`
{% extends "base.html" %}
{% load bootstrap5 %}
{% block content %}
<div class="container">
<h1>Log In</h1>
<form method="POST">
{% csrf_token %}
{% bootsrap_form form%}
<input type="submit" class="btn btn-default" value="Login">
</form>
 
</div>
 
{% endblock content %}`
```

What  noticed, i wrote bootstrap and the error has bootsrap in it omitting the 't' after 's' in the spelling of bootstrap, i made that error when i typed it in the first time and since then it has been returning the same error even though i have eited my template to correct the typo.
any help rendered would be highly appreciated

**Comment by zelenij** [comment]
Double check there are no other misspellings in your code.  Also, are you running in prod mode? In that case templates are cached and are not reloaded after edit.  Restart Django to force it to re-read the template.
