### ISSUE TITLE
Form rendering is not adapted to v5

### ISSUE THREAD

**Issue by jeriox** [zelenij/django-bootstrap-v5#2]
There were several changes on how to render forms in Bootstrap 5 (see the [migration guide](https://getbootstrap.com/docs/5.0/migration/#forms-2)) This library still renders forms in an v4 manner which looks rather ugly.

I'm gonna put up a PR to change the FORM_GROUP_CLASS to mb-3 as form-group was dropped.
But there are several other changes to consider like the removal of form-row/form-inline

**Comment by zelenij** [comment]
@jeriox sure, sounds like a good idea.

**Comment by zelenij** [comment]
Merged

**Comment by zelenij** [comment]
Pushed a new version. Also started watching the repository - I wasn't even aware the issue was open :)

**Comment by jeriox** [comment]
@zelenij do you plan on maintaining this repo? In the meantime, https://github.com/zostera/django-bootstrap5 is also work in progress

**Comment by zelenij** [comment]
@jeriox hmm, this is new.  I'll keep mine running for awhile, if that guy keeps updating his, I'll be fine to drop this.  No need for multiple versions :)

**Comment by jeriox** [comment]
well, it's not a guy but a company and they also made the original package that you forked and maintained it for several years, so I guess the odds are quite good that they'll do so in the future

**Comment by jeriox** [comment]
> 
> 
> well, it's not a guy but a company and they also made the original package that you forked and maintained it for several years, so I guess the odds are quite good that they'll do so in the future

@zelenij the other one has now been released as v1.0.0

**Comment by zelenij** [comment]
OK, if they keep supporting it, it's great news! I'm kinda busy anyway at the moment :)
