### ISSUE TITLE
access a local version when the CDN is not available (or local dev)

### ISSUE THREAD

**Issue by specialorange** [zelenij/django-bootstrap-v5#25]
Is there a way to override the settings file when the CDN is unavailable (ie during development) and to serve a local file instead?

**Comment by zelenij** [comment]
Yes you can. Look here:

https://github.com/zelenij/django-bootstrap-v5/blob/main/src/bootstrap5/bootstrap.py

If you create a setting BOOTSTRAP5 with keys, matching the defaults, and the values you want, they will be used instead.

**Comment by specialorange** [comment]
That doesn't really address when the CDN is unavailable, but I saw the setting/get what you are intending me to do.
