### ISSUE TITLE
RadioSelectButtonGroup shows bullets?

### ISSUE THREAD

**Issue by nerdoc** [zelenij/django-bootstrap-v5#27]
When rendering the [example from the widget docs](https://django-bootstrap-v5.readthedocs.io/en/latest/widgets.html), it looks like this:
![grafik](https://user-images.githubusercontent.com/2955584/179086457-b416f2e7-d581-464f-9e1d-509ac6d33412.png)

But I think it is supposed to look like in the official BS5 docs, like this:
![grafik](https://user-images.githubusercontent.com/2955584/179086806-abade675-df4e-462c-95dd-7b8118f03872.png)

I think the bullets are not supposed to be there. The HTML output differs from the recommended output in the BS5 docs: the label should IMHO not enclose the input...?

**Comment by nerdoc** [comment]
I think that the widget's template is old, maybe nobody used it, so nobody cared.

I updated it to the current BS5, It would look like this:
```django
<div{% if widget.attrs.id %} id="{{ widget.attrs.id }}"{% endif %} class="btn-group" role="group">
  {% for group, options, index in widget.optgroups %}
    {% for option in options %}
      <input type="{{ option.type }}" class="{{ widget.attrs.class|add:' btn-check' }}" autocomplete="off" name="{{ option.name }}" id="{{ option.attrs.id }}"{% if option.value != None %} value="{{ option.value|stringformat:'s' }}"{% if option.attrs.checked %} checked="checked"{% endif %}{% endif %}{% if widget.required %} required{% endif %}>
      <label class="btn btn-outline-primary" for="{{ option.attrs.id }}">{{ option.label }}</label>
    {% endfor %}
  {% endfor %}
</div>
```

Please tell me what you think - If you find it ok, I can make a PR too. BTW, I don't know why in the BS5 examples the `autocomplete="off"` is used.

**Comment by zelenij** [comment]
Care to create a PR? :)

**Comment by nerdoc** [comment]
Sure. Give me a few days... Do so use a frontend testing framework?

**Comment by nerdoc** [comment]
BTW - what is with [django-bootstrap5](https://github.com/zostera/django-bootstrap5/issues)? Why are there 2 projects? Can't you merge?

**Comment by zelenij** [comment]
Well, this repository is a fork of django-bootstrap4, while 5 didn't exist at the time.

**Comment by nerdoc** [comment]
Yes, I know, but not things are different. And it's double the effort, different bugs, and for developers using those repos its VERY unclear which one is the better. It's just a "try and error". OpenOffice/LibreOffice did not help much for both, Owncloud/Nextcloud neither. One will succeed in the end - but to make it good in the first place, a merging would be really helpful for all, even for you ;-)

**Comment by zelenij** [comment]
You are preaching to the converted - I'd be happy to merge etc.

**Comment by nerdoc** [comment]
Have you got a clue about the differences?

**Comment by nerdoc** [comment]
Should I open a new issue for that? I would be willing to help if I can
