### ISSUE TITLE
Archive this project.

### ISSUE THREAD

**Issue by suspiciousRaccoon** [zelenij/django-bootstrap-v5#34]
This project hasn't received commits in over 2 years and an actively maintained [repo](https://github.com/zostera/django-bootstrap5) for bootstrap 5 exists as well. If you're not interested in maintaining the project please consider archiving and adding the maintained repo to the README.md.

**Comment by zelenij** [comment]
Fair enough :) I don't have time to maintain the project at the moment, unfortunately
