### ISSUE TITLE
importlib-metadata version dependency?

### ISSUE THREAD

**Issue by kajala** [zelenij/django-bootstrap-v5#8]
Could importlib-metadata dependency be dropped? { version = "<3", python = "<3.9", optional = true }

E.g. twine 3.4.1 and keyring 23.0.0 require importlib-metadata>=3.6 which causes conflicts even if importlib-metadata is marked as optional in pyproject.toml

**Comment by zelenij** [comment]
I can't drop it (without changing more code) since this library became part of python only in 3.8. If you use 3.9, however, it won't even be installed, I think.  I did bump the version, so your immediate problems should be fixed.
